SQL Schema: Version 1.02

CREATE TABLE IF NOT EXISTS [*SCHEMA*].IFRIDGE_ITEM(
	item_id INT(11) NOT NULL AUTO_INCREMENT,
	item_name VARCHAR(100) DEFAULT NULL,
	quantity INT(11) DEFAULT NULL, 
	image VARCHAR(100) DEFAULT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	expiration INT(11) DEFAULT NULL,
	PRIMARY KEY (item_id)
);


CREATE TABLE IF NOT EXISTS [*SCHEMA*].IFRIDGE(
	ifridge_id INT(11) NOT NULL AUTO_INCREMENT,
	user_id INT(11) NOT NULL,
	temperature NUMERIC(5) NOT NULL,
	date DATETIME NOT NULL,
	PRIMARY KEY(ifridge_id)
);


CREATE TABLE IF NOT EXISTS [*SCHEMA*].IFRIDGE_USER(
	user_id INT(11) NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	email VARCHAR(320) NOT NULL UNIQUE,
	address	VARCHAR(320),
	ifridge_id INT(11) NOT NULL,
	PRIMARY KEY(user_id),
	FOREIGN KEY(ifridge_id) REFERENCES IFRIDGE(ifridge_id)
);

CREATE TABLE IF NOT EXISTS [*SCHEMA*].IFRIDGE_RECEIPE_CAT(
	cat_id INT(11) NOT NULL AUTO_INCREMENT,
	cat_name VARCHAR(30) NOT NULL,
	PRIMARY KEY(cat_id)
	
);

CREATE TABLE IF NOT EXISTS [*SCHEMA*].IFRIDGE_RECEIPE(
	receipe_id INT(11) NOT NULL AUTO_INCREMENT,
	receipe_name VARCHAR(30) NOT NULL,
	receipe_description VARCHAR(320) NOT NULL,
	email VARCHAR(320) NOT NULL UNIQUE,
	cat_id INT(11) NOT NULL, 
	PRIMARY KEY(receipe_id),
	FOREIGN KEY(cat_id) REFERENCES IFRIDGE_RECEIPE_CAT(cat_id)
);



CREATE TABLE IF NOT EXISTS [*SCHEMA*].IFRIDGE_RECEIPE_ITEM(
	receipe_id INT(11) NOT NULL,
	item_id INT(11) NOT NULL,
	FOREIGN KEY(receipe_id) REFERENCES IFRIDGE_RECEIPE(receipe_id),
	FOREIGN KEY(item_id) REFERENCES IFRIDGE_item(item_id)
);
